services:
  maxkb:
    image: registry.cn-shanghai.aliyuncs.com/ai_studio/maxkb:test11
    container_name: maxkb1
    entrypoint: ["/bin/bash"]
    command: ["/usr/bin/run-maxkb.sh"]
    ports:
      - "9870:8080"
    volumes:
      - /docker-app/maxkb/maxkb_postgresql:/var/lib/postgresql/data
      - /docker-app/maxkb/data:/opt/maxkb/app/data
      - /docker-app/maxkb/model:/opt/maxkb/model
      - /docker-app/maxkb/logs:/opt/maxkb/app/logs
    restart: unless-stopped